In [1]:
import seaborn as sns
flights = sns.load_dataset("flights")
df = flights.copy()

df.head

<bound method NDFrame.head of      year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]>

In [3]:
df.shape

(144, 3)

In [17]:
df.describe()

              year  passengers
count   144.000000  144.000000
mean   1954.500000  280.298611
std       3.464102  119.966317
min    1949.000000  104.000000
25%    1951.750000  180.000000
50%    1954.500000  265.500000
75%    1957.250000  360.500000
max    1960.000000  622.000000

In [13]:
df["passengers"].describe()

count    144.000000
mean     280.298611
std      119.966317
min      104.000000
25%      180.000000
50%      265.500000
75%      360.500000
max      622.000000
Name: passengers, dtype: float64

In [29]:
df = df.pivot("month","year","passengers")

TypeError: DataFrame.pivot() takes 1 positional argument but 4 were given

In [31]:
# cizgi grafik

import seaborn as sns
fmri = sns.load_dataset("fmri")

df = fmri.copy()
df.head()

  subject  timepoint event    region    signal
0     s13         18  stim  parietal -0.017552
1      s5         14  stim  parietal -0.080883
2     s12         18  stim  parietal -0.081033
3     s11         18  stim  parietal -0.046134
4     s10         18  stim  parietal -0.037970

In [33]:
df.shape

(1064, 5)

In [39]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
timepoint,1064.0,9.00000,5.479801,0.000000,4.00000,9.000000,14.000000,18.000000
signal,1064.0,0.00354,0.093930,-0.255486,-0.04607,-0.013653,0.024293,0.564985

In [41]:
df["timepoint"].describe()

count    1064.000000
mean        9.000000
std         5.479801
min         0.000000
25%         4.000000
50%         9.000000
75%        14.000000
max        18.000000
Name: timepoint, dtype: float64

In [43]:
df["signal"].describe()

count    1064.000000
mean        0.003540
std         0.093930
min        -0.255486
25%        -0.046070
50%        -0.013653
75%         0.024293
max         0.564985
Name: signal, dtype: float64

In [45]:
df.groupby("timepoint")["signal"].count()

timepoint
0     56
1     56
2     56
3     56
4     56
5     56
6     56
7     56
8     56
9     56
10    56
11    56
12    56
13    56
14    56
15    56
16    56
17    56
18    56
Name: signal, dtype: int64

In [47]:
df.groupby("signal").count()

           subject  timepoint  event  region
signal
-0.255486        1          1      1       1
-0.238474        1          1      1       1
-0.224351        1          1      1       1
-0.181241        1          1      1       1
-0.178510        1          1      1       1
...            ...        ...    ...     ...
 0.455575        1          1      1       1
 0.460896        1          1      1       1
 0.476055        1          1      1       1
 0.494787        1          1      1       1
 0.564985        1          1      1       1

[1064 rows x 4 columns]

In [49]:
df.groupby("timepoint")["signal"].describe()

,count,mean,std,min,25%,50%,75%,max
timepoint,,,,,,,,
0,56.0,-0.016662,0.028326,-0.064454,-0.039169,-0.018382,0.003539,0.074399
1,56.0,-0.025002,0.030641,-0.082174,-0.046299,-0.024533,-0.005388,0.063558
2,56.0,-0.012873,0.035440,-0.110565,-0.034944,-0.013183,0.009318,0.077277
3,56.0,0.034446,0.058260,-0.089708,-0.001157,0.028430,0.061840,0.185581
4,56.0,0.098194,0.092838,-0.046347,0.030912,0.070166,0.144911,0.346775
5,56.0,0.137725,0.123353,-0.017946,0.042762,0.096535,0.211638,0.476055
6,56.0,0.127515,0.137332,-0.054405,0.022409,0.068850,0.218919,0.564985
7,56.0,0.075660,0.129704,-0.108222,-0.016252,0.032486,0.144781,0.494787
8,56.0,0.013420,0.104216,-0.181241,-0.049453,-0.012834,0.030396,0.337143
9,56.0,-0.032041,0.072728,-0.152929,-0.075693,-0.038496,0.008717,0.221716
10,56.0,-0.053685,0.053148,-0.176453,-0.078893,-0.052906,-0.015302,0.089231
11,56.0,-0.058194,0.053828,-0.238474,-0.093127,-0.045699,-0.022522,0.030528
12,56.0,-0.052526,0.056991,-0.255486,-0.090391,-0.042294,-0.016239,0.055766
13,56.0,-0.043532,0.053598,-0.224351,-0.069285,-0.031612,-0.012958,0.059510
14,56.0,-0.033660,0.045983,-0.169312,-0.055110,-0.022165,-0.006797,0.050133
15,56.0,-0.025880,0.039092,-0.134828,-0.050536,-0.018207,0.000486,0.047102
16,56.0,-0.022414,0.035035,-0.131641,-0.041122,-0.020777,-0.001380,0.057105
17,56.0,-0.021368,0.034797,-0.121574,-0.042946,-0.017070,-0.000026,0.073757
18,56.0,-0.021867,0.036322,-0.103513,-0.046781,-0.020225,-0.002821,0.090520

In [ ]:
sns.lineplot(x="timepoint", y="signal", data=df)

In [1]:
# Basit zaman serisi grafigi
!pip install pandas_datareader

Collecting pandas_datareader
  Downloading pandas_datareader-0.10.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: lxml in c:\users\lenovo\anaconda3\lib\site-packages (from pandas_datareader) (5.2.1)
Requirement already satisfied: pandas>=0.23 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas_datareader) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas_datareader) (2.32.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2025.4.26)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.16.0)
Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
Installing collected packages: pandas_datareader
Successfully installed pandas_datareader-0.10.0

In [13]:
import pandas_datareader as pr

In [15]:
df = pr.get_data_yahoo("AAPL",start="2016-01-01",end="2019-08-25")
df.head()

RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/AAPL/history?period1=1451610000&period2=1566781199&interval=1d&frequency=1d&filter=history
Response Text:
b'<html><meta charset=\'utf-8\'>\n<script>\nif(window != window.top){\ndocument.write(\'<p>Content is currently unavailable.</p><img src="//geo.yahoo.com/p?s=1197757039&t=\'\n    + new Date().getTime() + \'&_R=\'\n    + encodeURIComponent(document.referrer)\n    + \'&err=404\'\n    + \'" width="0px" height="0px"/>\');\n}else{\nwindow.location.replace(\'https://\' + window.location.host + \'/?err=404\');\n}\n</script>\n<noscript>\n<META http-equiv="refresh" content="0;URL=https://finance.yahoo.com/?err=404">\n</noscript></html>'