In [5]:
import numpy as np
import pandas as pd

V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])

df = pd.DataFrame(
    {
        "V1":V1,
        "V2":V2,
        "V3":V3,
    }    
)
df = df.astype(float)

df

    V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [7]:
# Standizasyon
from sklearn import preprocessing

In [9]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [11]:
df.mean()

V1    4.4
V2    7.8
V3    8.6
dtype: float64

In [13]:
# Normalizasyon : Değerleri 0-1 arasına dönüştürmek icin kullanılır.
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

In [21]:
# min-max Dönüşümü
scaler = preprocessing.MinMaxScaler(feature_range =(10,20))

In [23]:
scaler

MinMaxScaler(feature_range=(10, 20))

In [25]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

In [27]:
# Değişken Dönüşümleri. Mevcut yapıyı bozmadan dönüşüm yapabiliriz.
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# 0-1 dönüşümü en sık kullanılan dönüşümlerden bir tanesi cinsiyeti 0 ve 1 olarak değiştirebiliriz.

In [30]:
# numeric formatta istenirse 
from sklearn.preprocessing import LabelEncoder

lbe = LabelEncoder()

In [32]:
lbe.fit_transform(df["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [34]:
df["yeni_sex"] = lbe.fit_transform(df["sex"])

In [36]:
df

     total_bill   tip     sex smoker   day    time  size  yeni_sex
0         16.99  1.01  Female     No   Sun  Dinner     2         0
1         10.34  1.66    Male     No   Sun  Dinner     3         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1
242       17.82  1.75    Male     No   Sat  Dinner     2         1
243       18.78  3.00  Female     No  Thur  Dinner     2         0

[244 rows x 8 columns]

In [38]:
# 1 ve Diğerleri (0) dönüşümü
df.head()

   total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0

In [40]:
import numpy as np

df["yeni_day"] = np.where(df["day"].str.contains("Sun"),1,0)

In [42]:
df

     total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day
0         16.99  1.01  Female     No   Sun  Dinner     2         0         1
1         10.34  1.66    Male     No   Sun  Dinner     3         1         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0         1
..          ...   ...     ...    ...   ...     ...   ...       ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0

[244 rows x 9 columns]

In [46]:
# çok sınıflı dönüşüm
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [50]:
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])